### ISSUE TITLE
Wrong copyright in LICENSE file

### ISSUE THREAD

**Issue by NiklasLehnfeld** [google/eme-encryption-scheme-polyfill#20]
You didn't change the copyright placeholder at the bottom of the LICENSE file.

### Expected 
Copyright notice with year and name filled

### Actual
Copyright placeholder
Copyright [yyyy] [name of copyright owner]

**Comment by joeyparrish** [comment]
You may have misread the LICENSE file.  Immediately above the part you are referring to, you will find this context (emphasis added by me):

> APPENDIX: How to apply the Apache License to your work.
>
> **To apply the Apache License to your work, attach the following
> boilerplate notice**, with the fields enclosed by brackets "[]"
> replaced with your own identifying information. (Don't include
> the brackets!)  **The text should be enclosed in the appropriate
> comment syntax for the file format.** We also recommend that a
> file or class name and description of purpose be included on the
> same "printed page" as the copyright notice for easier
> identification within third-party archives.

You will find that an appropriate copyright notice does appear in our source files.  The template in the LICENSE file is merely demonstrating the recommended format for that copyright notice.

Does this help?

**Comment by NiklasLehnfeld** [comment]
Ah, okay. Thanks for pointing that out! 🙂
